### ISSUE TITLE
Retrieve Feed and Search Integration (Frontend and backend)

### ISSUE THREAD

**Issue by Inge505** [LapseMP/lapse-grp3-2023#19]
- [ ] See Feed
- [ ]  Trending _(Inge)_
  - [ ] UI interaction with state
  - [ ] State
  - [ ] Client-side API
  - [ ] API core function
  - [ ] Query
  - [ ] Data Access via repository
- [x] Following_(Inge)_
  - [x] UI interaction with state
  - [x] State
  - [x] Client-side API to FireStore
- [x] Search by Hashtag _(Priyul)_
  - [x] UI interaction with state
  - [x] State
  - [x] Client-side API to FireStore
- [x] Search By UserId _(Mark)_
  - [x] UI interaction with state
  - [x] State
  - [x] Client-side API to FireStore
- [ ] Tests:
  - [ ] Unit Test (everyone to write their own)
  - [ ] Integration (everyone can help - Janco responsible for oversight)
  - [ ] UI test (Janco)

**Comment by Inge505** [comment]
When do you all want to work on this? 
The API side is more or less in place, so the front end must check whether it works, then we can start debugging and fixing once we know what's broken, if anything.
So @JulianPienaar and @RoninBrookesTuks maybe you guys can let us know when you've had time to check whether you can link with the state and retrieve posts, if you need any help using the state @Priyul and I did it, so just shout

**Comment by JulianPienaar** [comment]
Me and Ronin are going to work on this today at 16:00. We'll be sure to let @Inge505 or @Priyul know if we need help.
