### ISSUE TITLE
WireFrame Design

### ISSUE THREAD

**Issue by Inge505** [LapseMP/lapse-grp3-2023#2]

**Comment by chrislom12** [comment]
- [ ] Sketch 3 designs
- [ ] Rough Wireframes
- [ ] Detailed prototype

**Comment by chrislom12** [comment]
**Completed first rough design:**
[Wireframe #1](https://xd.adobe.com/view/1e567048-2044-482d-8b86-b4ca696d62ea-4b05/)

**Comment by Daniel-Bezuidenhout** [comment]
Great design. Possibly have a splash page that auto-transitions to login page instead of having the login as the landing page?

**Comment by RoninBrookesTuks** [comment]
![Image](https://user-images.githubusercontent.com/126901461/224128355-0d0e041b-55d5-4f46-8ce3-5aac1a370712.png)

**Comment by chrislom12** [comment]
I think overall both wireframes are pretty similar. Here are some of the things I really like and will try to add into the final design:
- Create Page: plus sign for creating/adding more posts
- Profile: showcasing minutes on the profile
- Market: Like and dislike bars
- Overall: Infinity background

**Comment by chrislom12** [comment]
Here is the first version of the splash, login, trending, following, comment section, search page, search #feed
[Clickable Prototype](https://xd.adobe.com/view/883e28a7-9a28-4bef-82d0-8482b921d3f4-dd6d/)

For the prototype, only the first post on trending is coded to have access to the other views (see video):
[Prototype video link](https://drive.google.com/file/d/1qEwV2VI534ln_25E0W4hT7XIFbK3JeGf/view?usp=share_link)

**Comment by Daniel-Bezuidenhout** [comment]
I really like the look and colour scheme. I think it may look better with a slight margin on the sides of posts so that they are not hugging the screen.

**Comment by chrislom12** [comment]
> I really like the look and colour scheme. I think it may look better with a slight margin on the sides of posts so that they are not hugging the screen.

I get what you mean, this is what you're suggestion looks like. I feel doing it like this makes it feel like less of a feed, and just singular items on divs
![image](https://user-images.githubusercontent.com/105363824/224484969-3ea2194e-c47e-43c0-bfb5-7116bea518c4.png)

I propose something a bit more plain and regular, because I think the curved edges werent really working
![image](https://user-images.githubusercontent.com/105363824/224484992-d1480fe5-d369-4ce8-8292-1b914e94ec7c.png)

**Comment by chrislom12** [comment]
I also dont think the green works that well as a background, what about this?

![image](https://user-images.githubusercontent.com/105363824/224485714-b95b1c0d-d448-4d66-9827-7b266695436a.png)

**Comment by Daniel-Bezuidenhout** [comment]
That actually looks great. Keeps the continuous "feed" feel and I think it looks better than my previous suggestion

**Comment by chrislom12** [comment]
Added the rest of the screens
[Clickable prototype](https://xd.adobe.com/view/883e28a7-9a28-4bef-82d0-8482b921d3f4-dd6d/)

Video:
[video link](https://drive.google.com/file/d/1qEwV2VI534ln_25E0W4hT7XIFbK3JeGf/view?usp=share_link)

Please give input on everything. For the settings page, i need some input on what to do with the empty space

**Comment by Inge505** [comment]
Absolutely love the design. 

Just a thought, not so much in terms of design, but in the implementation graphs may be a difficult thing to add. It requires keeping track of every interaction and returning it, which is a bit involved from a backend point of view. 

Maybe for now we can just display the total earnings, maybe "owner earnings" and selling price per post? And if we have a good first product we add the graphs as a "wow". Just a thought, maybe some of the other backend members can comment

**Comment by RoninBrookesTuks** [comment]
Everything in the design looks really solid Chris I think you could just use the infinity logo in settings as you did for logo or just do away with the infinity sign in notifications it seems a bit out of place and random. The color scheme works well I think having it be white with dark green and light blue as a compliment is a good idea it keeps things looking neat and formal. Just want to confirm that the portfolio, are those your posts with the statistics?

**Comment by chrislom12** [comment]
> Absolutely love the design.
> 
> Just a thought, not so much in terms of design, but in the implementation graphs may be a difficult thing to add. It requires keeping track of every interaction and returning it, which is a bit involved from a backend point of view.
> 
> Maybe for now we can just display the total earnings, maybe "owner earnings" and selling price per post? And if we have a good first product we add the graphs as a "wow". Just a thought, maybe some of the other backend members can comment

Yeah I also thought the graph might be a bit of a stretch, but luckily it will be easy to add if we end up wanting to do it

**Comment by chrislom12** [comment]
> Everything in the design looks really solid Chris I think you could just use the infinity logo in settings as you did for logo or just do away with the infinity sign in notifications it seems a bit out of place and random. The color scheme works well I think having it be white with dark green and light blue as a compliment is a good idea it keeps things looking neat and formal. Just want to confirm that the portfolio, are those your posts with the statistics? For the settings page we can also add placeholder settings such as "clear chat history", "Block contacts" , "Dark mode". Or just the infinity sign background if possible but it might look also out of place. OR do away with the settings page altogether and have you be able to change your name directly from the profile. As in tap your name to change your name, tap on the gear to change your email and password. But I think as far as what we need to do based on the requirements this is perfect, well done!

- Yeah the portfolio are the statistics posts
- I agree that the infinity sign looks out of place, maybe for now we just leave the whitespace there, and maybe later on inspiration strikes during development, but it's not the end of the world to have whitespace.
- For converting the settings into options on the home page, i'm hesitant to do that, simply cus it doesn't feel intuitive, since we  are doing the app on a pc one could 'cheat' and have some kind of hover popup effect to show that you could edit the username, but one wouldnt be able to implement that on a real mobile app
