### ISSUE TITLE
Interact with Posts Integration (Frontend and backend)

### ISSUE THREAD

**Issue by Inge505** [LapseMP/lapse-grp3-2023#20]
- [ ] Like a Post
  - [ ] UI interaction with state
  - [ ] State
  - [ ] Client-side API
  - [ ] API core function
  - [ ] Commands and Events
  - [ ] Data Access via repository
- [ ] Comment on a post
  - [ ] UI interaction with state
  - [ ] State
  - [ ] Client-side API
  - [ ] API core function
  - [ ] Commands and Events
  - [ ] Data Access via repository
- [ ] Buy a post
  - [ ] UI interaction with state
  - [ ] State
  - [ ] Client-side API
  - [ ] API core function
  - [ ] Commands and Events
  - [ ] Data Access via repository
- [ ] Tests:
  - [ ] Unit Test (everyone to write their own)
  - [ ] Integration (everyone can help - Janco responsible for oversight)
  - [ ] UI test (Janco)

**Comment by PaulPilane** [comment]
> * [x]  Like a Post
> * [x]  Comment on a post
> * [x]  Buy a post
> * [ ]  Tests:
>   
>   * [ ]  Unit Test (everyone to write their own)
>   * [ ]  Integration (everyone can help - Janco responsible for oversight)
>   * [ ]  UI test (Janco)

Also, please double check on the repo if I have indeed done the correct thing and swiftly get back to me
