### ISSUE TITLE
Privacy policy + TOS + About

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#33]
The Privacy Policy and Terms of Service on the welcome page currently have no content. We could as ChatGPT to write up a basic one. I think this falls under Business analysis? The "What is Lapse" button on the login screen also does nothing.

**Comment by JanSpies82** [comment]
The documents on the google drive look good to me as well.
Do you mind adding the privacy statement and the terms of service so long @Daniel-Bezuidenhout ? These two pages already have pages created, the content just needs to be inserted and formatted. I'll create a separate issue for the about, since the page with all the routing has to be created first so the UI guys can do that @JulianPienaar @RoninBrookesTuks

**Comment by Daniel-Bezuidenhout** [comment]
Can do, will be done this weekend

**Comment by Daniel-Bezuidenhout** [comment]
Nevermind, I see Julian and you got to it 😆
