### ISSUE TITLE
Timer component

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#35]
The timer component on all of the screens currently has no functionality and should display the user's remaining time and tick down.

**Comment by JulianPienaar** [comment]
I have created a component in the profile UI folder called time-badge. The time should be initialized on login/register and then the setInterval variable as well as the remaining time should be sent to each page as a user navigates through the app. Unless there is a way to for the component to some global variable which would also be set on login/register.

**Comment by PaulPilane** [comment]
If you want to persist data as you navigate through different pages using the navigation method we currently use, you will have to declare a NavigationExtra and pass it on the this.router.navigate, 

An example: 
Const navigationExtra: NavigationExtra = {
 value = 'time' 
}

this.router.navigate(['/profile']. NavigationExtra)

In this way, as you navigate to a different page, you will navigate with that data. 'Time' will be persisted to profile page.
