### ISSUE TITLE
Create page

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#37]
The following are important issues:
- [x] No error message when creating a post without attaching an image
- [x] Showing confirmation message when post is successfully uploaded  
- [x] Clear the create post form data after a post has been uploaded

The following are optional features to improve user experience:

- [x] Disable the starting price components if the post is not for sale
- [x] Making it clearer to the user which hashtag is actually selected for the post (colour maybe?)
- [x] Redirect to different screen after post is uploaded

**Comment by chrislom12** [comment]
All tasks have been finished
