### ISSUE TITLE
Add loading animation

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#39]
We should consider adding a small loading animation to the pages when performing slow actions like loading feed or uploading a post so that the user knows the system is actually alive

**Comment by chrislom12** [comment]
@JulianPienaar @RoninBrookesTuks 

Could one of you help out with adding a gif loading screen? I imagine it would essentially take up the screen till the content is loaded, but i'm not sure how to go about implementing that:

it looks like this:
![Image](https://user-images.githubusercontent.com/105363824/233835813-e68c4d50-1f1a-4dc7-9012-30f7b0736753.gif)
