### ISSUE TITLE
Edit README

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#45]
I think we should change the readme of the repository to be more about our actual project and not Arne's generated template. We could still include the compilation commands and some of the setup, but I think it is important to explain our project in the same way as demo 1

**Comment by Inge505** [comment]
Sounds good, will get to it tomorrow

**Comment by chrislom12** [comment]
@Inge505 if you maybe wanna do the content of the readme, i'll make it look good with some fancy stuff, kind of in the way to show it off on our githubs aswell

**Comment by Inge505** [comment]
I've started editing it, just check the pull request. I'll add some more details. Not sure what to cut and what to leave

**Comment by Inge505** [comment]
I was thinking we could add a brief directory structure. Link all our wikis and google docs and maybe add the demo videos. At least add the nice to look at stuff. What do you think @chrislom12
