### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#54]
The current documentation is very outdated and references features that do not exist (eg following).

**Comment by JanSpies82** [comment]
At the [Documentation](https://github.com/LapseMP/lapse-grp3-2023/wiki/4.-Documentation) :

- [x]  User Interaction: I don't think the marketplace exists (or at least we don't differentiate between "feed" and "marketplace")
- [x] The Economy: do we still charge the user to create a post?
- [x] [Drive](https://docs.google.com/document/d/17qjp9B8DnrNBGhRxCDaeWYpsziJxXI8FT9sBEJ6DMpU/edit) : check my suggested updates

**Comment by JanSpies82** [comment]
At the [API](https://github.com/LapseMP/lapse-grp3-2023/wiki/2.-API-(States-and-Client-API))

- [x] Remove the message saying it is a draft or replace with final version

**Comment by ChrisMitt** [comment]
Database documentation has been updated and entities have been added to the wiki
