### ISSUE TITLE
Integrate cypress testing

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#59]
Cypress testing should be integrated into the project with a test for every screen.

**Comment by JanSpies82** [comment]
Could you guys check whether you can get the basic cypress running?
I've followed the ChatGPT steps on how to integrate cypress into an nx project using yarn and I installed it together with all its dependencies, but when I run `yarn run cypress open`  it starts doing something but ultimately ends up loading forever (yes I have restarted the process a few times). Let me know if you have more luck than me...

**Comment by TriumphNdlovu** [comment]
I did some testing for authentication and the welcome page links...

i also had to change the cypress.config.ts file cause it wasn't working and had an error on my side
