### ISSUE TITLE
Portfolio page data

### ISSUE THREAD

**Issue by JanSpies82** [LapseMP/lapse-grp3-2023#67]
The portfolio page correctly shows that a post owned by you got a like, but it does not show the amount of minutes gained by the post.

**Comment by Inge505** [comment]
I think it should still show owner gained time. Pretty sure it's not there yet

**Comment by chrislom12** [comment]
In the meantime to remedy this, since we removed comments, i just took the number of likes and said they gained that amount of minutes (this is ofc for the post lifetime, not just for the owner lifetime, so not really that useful lol but it's a stat that we can show)
