### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by Inge505** [LapseMP/lapse-grp3-2023#7]
WireFrame to Ionic translation

**Comment by chrislom12** [comment]
Branding and Icons:
[Branding and Icons.zip](https://github.com/LapseMP/lapse-grp3-2023/files/11072315/Branding.and.Icons.zip)

**Comment by chrislom12** [comment]
logo animation:


![Image](https://user-images.githubusercontent.com/105363824/227804804-512489ee-b3b8-445d-8ac7-82d134bdf1be.gif)
